version: "3.8"

services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - mean-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: <DOCKERHUB_USERNAME>/mean-backend:latest
    environment:
      - MONGO_URL=mongodb://mongo:27017/mean-db
      - PORT=3000
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    networks:
      - mean-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health" ]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: <DOCKERHUB_USERNAME>/mean-frontend:latest
    depends_on:
      - backend
    networks:
      - mean-net
    restart: unless-stopped
    # We'll not expose frontend directly if using proxy; but map if you want:
    ports:
      - "8080:80"

  proxy:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - mean-net
    restart: unless-stopped

volumes:
  mongo-data:

networks:
  mean-net:
